apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo-dotnet
  template:
    metadata:
      labels:
        app: hola-mundo-dotnet
    spec:
      containers:
        - name: hola-mundo-dotnet
          image: k8sdotnetaksdu9q.azurecr.io/hola-mundo-dotnet:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/data
              name: sqlite-storage
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
