apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-dotnet-svc
spec:
  selector:
    app: hola-mundo-dotnet
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
