name: Build and Push Docker image to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name k8sdotnetaksdu9q

    - name: Build and Push Docker image
      run: |
        docker build -t k8sdotnetaksdu9q.azurecr.io/hola-mundo-dotnet:latest -f src/K8sDotnetApi/Dockerfile .
        docker push k8sdotnetaksdu9q.azurecr.io/hola-mundo-dotnet:latest
