name: CI Build & Push
on:
  workflow_run:
    workflows: ["Terraform Create Infra"]
    types: [completed]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Get ACR login server from terraform output
        id: get_acr
        run: echo "acr=$(terraform -chdir=infra output -raw acr_login_server)" >> $GITHUB_OUTPUT

      - name: Docker Build & Push
        env:
          ACR_LOGIN_SERVER: ${{ steps.get_acr.outputs.acr }}
        run: |
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"
          az acr login --name $(echo $ACR_LOGIN_SERVER | cut -d'.' -f1)
          docker build -t $ACR_LOGIN_SERVER/hola-mundo-dotnet:latest ./src/K8sDotnetApi
          docker push $ACR_LOGIN_SERVER/hola-mundo-dotnet:latest
