name: CI Build & Push

on:
  workflow_run:
    workflows: ["Terraform Create Infra"]
    types: [completed]

env:
  ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
  ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
  ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get ACR login server from Terraform output
        id: get_acr
        run: |
          terraform -chdir=infra init -input=false
          ACR_LOGIN_SERVER=$(terraform -chdir=infra output -raw acr_login_server)
          echo "acr_login_server=$ACR_LOGIN_SERVER" >> $GITHUB_OUTPUT

      - name: Docker Build & Push
        env:
          ACR_LOGIN_SERVER: ${{ steps.get_acr.outputs.acr_login_server }}
        run: |
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"
          ACR_NAME=$(echo $ACR_LOGIN_SERVER | cut -d'.' -f1)
          az acr login --name $ACR_NAME
          docker build -t $ACR_LOGIN_SERVER/hola-mundo-dotnet:latest -f src/K8sDotnetApi/Dockerfile .
          docker push $ACR_LOGIN_SERVER/hola-mundo-dotnet:latest
